### ISSUE TITLE
didn't output any time expression

### ISSUE THREAD

**Issue by Sannndy0000** [amineabdaoui/python-heideltime#3]
Hi,

I just cloned and ran as instructed, but the output to your demo is:

```
'<?xml version="1.0"?>
<!DOCTYPE TimeML SYSTEM "TimeML.dtd">
<TimeML>
Neil Armstrong was born in 1930
</TimeML>
'

```
Seems it's not finding any time mention. Any idea?

Thank you!

**Comment by amineabdaoui** [comment]
Hi,

Sorry for my late reply. 
I didn't receive email notifications about this repo. 

Have you been able to load the wrapper properly with a given language? 

One possible cause may be related to TreeTagger.
Can you test it using the following commands:
```bash
cd TreeTagger/
echo 'Hello world!' | cmd/tree-tagger-english
```
