### ISSUE TITLE
Cannot start HeidelTime

### ISSUE THREAD

**Issue by chlor** [amineabdaoui/python-heideltime#4]
Hi,

I installed pip install python-heideltime-krypton==0.0.2 

and when I start a blank python file with your Demo example I have the following error:
Traceback (most recent call last):
  File "heideltime.py", line 2, in <module>
    import HeidelTime
  File "/usr/local/lib/python3.8/dist-packages/HeidelTime/__init__.py", line 14, in <module>
    'english':heideltime_resources.Language.ENGLISH,
AttributeError: Java package 'de.unihd.dbs.uima.annotator.heideltime.resources' is not valid

Do you have a solution or a tip for the missing resource?

Best regards, Christina

**Comment by amineabdaoui** [comment]
Hi @chlor 

Sorry for this very late reply. 
I was not receiving email notifications. 

Have you tried using this repo directly?

I haven't published any pip dependency, so I am not aware of this one. 
If you have access to their code, you can check whether they load the [heideltime_resources](https://github.com/amineabdaoui/python-heideltime/blob/master/HeidelTime/__init__.py#L9) properly using jpype and whether the heideltime jar file is included in their distribution.
